package uniProject.carShowroomManagementSystem.validationRule.brand;

import org.springframework.stereotype.Component;

import lombok.RequiredArgsConstructor;
import uniProject.carShowroomManagementSystem.business.BrandService;
import uniProject.carShowroomManagementSystem.exception.BaseException;
import uniProject.carShowroomManagementSystem.exception.BaseValidationException;
import uniProject.carShowroomManagementSystem.exception.BrandServiceOperationException;
import uniProject.carShowroomManagementSystem.exception.ControllerOperationException;

@Component
@RequiredArgsConstructor
public class BrandValidatorImpl implements BrandValidator{

}
